import { Component, OnInit } from '@angular/core';
import { TrackMode } from '../../../services/trackMode.service';
import { TrackCurrency} from '../../../services/trackCurrency.service';
import {CalendarModule} from 'primeng/primeng';
import { MarketplaceService } from '../../../services/marketplace-services/marketplace.service';

@Component({
  selector: 'app-pub-marketplace',
  templateUrl: './pub-marketplace.component.html',
  styleUrls: ['./pub-marketplace.component.css']
})
export class PubMarketplaceComponent implements OnInit {  rangeValues2= [10,50];
  rangeValues3= [5,50];
  filterUsed = false;
  dt1 :any;
  dt2 :any;
  size : any=10;
  currencyType:string="";
  Adtype:any="Banner Top";
  genre:any="Movies";
  array:any;
  array2:any;
  displayedGenre:any="";
  displayedadType:any="";
  messageArray:any;
  selectedList:any =[];
  notEmpty = true;
  adlistings :any =[
{"username": "User8", "cpi": "39", "name": "ToyStory1listing", "ask_date_to": "2017-09-17", "currency": "eqc", "adname": "ToyStory1", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-08-16", "cpm": "50"},
{"username": "User9", "cpi": "17", "name": "left-for-dead2listing", "ask_date_to": "2017-09-22", "currency": "xqc", "adname": "left-for-dead2", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-12", "cpm": "42"},
{"username": "User5", "cpi": "27", "name": "Honda3listing", "ask_date_to": "2017-10-08", "currency": "xqc", "adname": "Honda3", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-09-03", "cpm": "30"},
{"username": "User9", "cpi": "20", "name": "GameOfThrones4listing", "ask_date_to": "2017-08-23", "currency": "eqc", "adname": "GameOfThrones4", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-17", "cpm": "42"},
{"username": "User1", "cpi": "39", "name": "left-for-dead5listing", "ask_date_to": "2017-09-08", "currency": "xqc", "adname": "left-for-dead5", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-08-04", "cpm": "11"},
{"username": "User5", "cpi": "30", "name": "left-for-dead6listing", "ask_date_to": "2017-09-22", "currency": "xqc", "adname": "left-for-dead6", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-13", "cpm": "33"},
{"username": "User5", "cpi": "46", "name": "Diningx7listing", "ask_date_to": "2017-08-25", "currency": "xqc", "adname": "Diningx7", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-07-16", "cpm": "33"},
{"username": "User7", "cpi": "36", "name": "xx8listing", "ask_date_to": "2017-12-11", "currency": "xqc", "adname": "xx8", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-10-08", "cpm": "18"},
{"username": "User3", "cpi": "12", "name": "Counterstrike9listing", "ask_date_to": "2017-09-22", "currency": "eqc", "adname": "Counterstrike9", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-17", "cpm": "37"},
{"username": "User1", "cpi": "13", "name": "Dining10listing", "ask_date_to": "2017-09-14", "currency": "eqc", "adname": "Dining10", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-07-07", "cpm": "28"},
{"username": "User2", "cpi": "21", "name": "Volvo11listing", "ask_date_to": "2017-08-19", "currency": "xqc", "adname": "Volvo11", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-18", "cpm": "24"},
{"username": "User5", "cpi": "28", "name": "Diningx12listing", "ask_date_to": "2017-09-16", "currency": "xqc", "adname": "Diningx12", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-07-08", "cpm": "8"},
{"username": "User5", "cpi": "18", "name": "Honda13listing", "ask_date_to": "2017-09-22", "currency": "xqc", "adname": "Honda13", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-07-17", "cpm": "7"},
{"username": "User9", "cpi": "16", "name": "newDining14listing", "ask_date_to": "2017-11-13", "currency": "eqc", "adname": "newDining14", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-10-07", "cpm": "7"},
{"username": "User8", "cpi": "36", "name": "InfinityWar15listing", "ask_date_to": "2017-12-18", "currency": "xqc", "adname": "InfinityWar15", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-10-08", "cpm": "48"},
{"username": "User1", "cpi": "43", "name": "Dota216listing", "ask_date_to": "2017-11-12", "currency": "xqc", "adname": "Dota216", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-10-11", "cpm": "11"},
{"username": "User6", "cpi": "22", "name": "ToyStory17listing", "ask_date_to": "2017-09-20", "currency": "eqc", "adname": "ToyStory17", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-07-11", "cpm": "27"},
{"username": "User8", "cpi": "47", "name": "InfinityWar18listing", "ask_date_to": "2017-11-13", "currency": "xqc", "adname": "InfinityWar18", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-09-03", "cpm": "20"},
{"username": "User2", "cpi": "20", "name": "Call-Of-Duty19listing", "ask_date_to": "2017-11-12", "currency": "eqc", "adname": "Call-Of-Duty19", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-07", "cpm": "14"},
{"username": "User1", "cpi": "17", "name": "Dota220listing", "ask_date_to": "2017-09-15", "currency": "xqc", "adname": "Dota220", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-09", "cpm": "9"},
{"username": "User7", "cpi": "12", "name": "Call-Of-Duty21listing", "ask_date_to": "2017-11-22", "currency": "xqc", "adname": "Call-Of-Duty21", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-10-14", "cpm": "21"},
{"username": "User5", "cpi": "19", "name": "Dining22listing", "ask_date_to": "2017-11-09", "currency": "eqc", "adname": "Dining22", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-10-05", "cpm": "46"},
{"username": "User4", "cpi": "22", "name": "GoodFellas23listing", "ask_date_to": "2017-12-12", "currency": "xqc", "adname": "GoodFellas23", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-10-11", "cpm": "18"},
{"username": "User5", "cpi": "49", "name": "GameOfThrones24listing", "ask_date_to": "2017-09-22", "currency": "eqc", "adname": "GameOfThrones24", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-20", "cpm": "5"},
{"username": "User9", "cpi": "31", "name": "left-for-dead25listing", "ask_date_to": "2017-12-26", "currency": "xqc", "adname": "left-for-dead25", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-10-18", "cpm": "20"},
{"username": "User3", "cpi": "44", "name": "GameOfThrones26listing", "ask_date_to": "2017-09-04", "currency": "eqc", "adname": "GameOfThrones26", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-03", "cpm": "40"},
{"username": "User5", "cpi": "48", "name": "Nissan27listing", "ask_date_to": "2017-09-14", "currency": "xqc", "adname": "Nissan27", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-10", "cpm": "13"},
{"username": "User4", "cpi": "38", "name": "Volvo28listing", "ask_date_to": "2017-10-04", "currency": "xqc", "adname": "Volvo28", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-08-01", "cpm": "31"},
{"username": "User5", "cpi": "48", "name": "newDining29listing", "ask_date_to": "2017-09-10", "currency": "eqc", "adname": "newDining29", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-07-07", "cpm": "20"},
{"username": "User5", "cpi": "30", "name": "GameOfThrones30listing", "ask_date_to": "2017-12-12", "currency": "xqc", "adname": "GameOfThrones30", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-10-05", "cpm": "29"},
{"username": "User7", "cpi": "33", "name": "Godfather31listing", "ask_date_to": "2017-11-13", "currency": "eqc", "adname": "Godfather31", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-10-12", "cpm": "26"},
{"username": "User3", "cpi": "10", "name": "Overwatch32listing", "ask_date_to": "2017-11-14", "currency": "eqc", "adname": "Overwatch32", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-09-05", "cpm": "22"},
{"username": "User9", "cpi": "49", "name": "GoodFellas33listing", "ask_date_to": "2017-09-14", "currency": "xqc", "adname": "GoodFellas33", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-06", "cpm": "36"},
{"username": "User8", "cpi": "16", "name": "Honda34listing", "ask_date_to": "2017-12-09", "currency": "eqc", "adname": "Honda34", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-10-01", "cpm": "19"},
{"username": "User3", "cpi": "32", "name": "Overwatch35listing", "ask_date_to": "2017-11-19", "currency": "xqc", "adname": "Overwatch35", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-13", "cpm": "14"},
{"username": "User4", "cpi": "49", "name": "GameOfThrones36listing", "ask_date_to": "2017-08-29", "currency": "xqc", "adname": "GameOfThrones36", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-20", "cpm": "50"},
{"username": "User3", "cpi": "42", "name": "Call-Of-Duty37listing", "ask_date_to": "2017-11-11", "currency": "xqc", "adname": "Call-Of-Duty37", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-10-06", "cpm": "42"},
{"username": "User3", "cpi": "46", "name": "Dining38listing", "ask_date_to": "2017-09-12", "currency": "eqc", "adname": "Dining38", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-08-02", "cpm": "25"},
{"username": "User4", "cpi": "18", "name": "Honda39listing", "ask_date_to": "2017-09-12", "currency": "xqc", "adname": "Honda39", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-05", "cpm": "50"},
{"username": "User7", "cpi": "50", "name": "InfinityWar40listing", "ask_date_to": "2017-10-14", "currency": "eqc", "adname": "InfinityWar40", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-09", "cpm": "21"},
{"username": "User3", "cpi": "29", "name": "left-for-dead41listing", "ask_date_to": "2017-11-20", "currency": "xqc", "adname": "left-for-dead41", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-16", "cpm": "47"},
{"username": "User7", "cpi": "19", "name": "Godfather42listing", "ask_date_to": "2017-09-23", "currency": "xqc", "adname": "Godfather42", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-08-13", "cpm": "34"},
{"username": "User3", "cpi": "36", "name": "Tesla43listing", "ask_date_to": "2017-09-14", "currency": "eqc", "adname": "Tesla43", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-07-12", "cpm": "38"},
{"username": "User2", "cpi": "26", "name": "GoodFellas44listing", "ask_date_to": "2017-12-10", "currency": "xqc", "adname": "GoodFellas44", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-10-08", "cpm": "23"},
{"username": "User8", "cpi": "26", "name": "GameOfThrones45listing", "ask_date_to": "2017-09-04", "currency": "xqc", "adname": "GameOfThrones45", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-07-03", "cpm": "15"},
{"username": "User6", "cpi": "32", "name": "half-life-346listing", "ask_date_to": "2017-09-19", "currency": "eqc", "adname": "half-life-346", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-07-12", "cpm": "27"},
{"username": "User2", "cpi": "39", "name": "xx47listing", "ask_date_to": "2017-08-13", "currency": "eqc", "adname": "xx47", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-07-06", "cpm": "49"},
{"username": "User2", "cpi": "50", "name": "ToyStory48listing", "ask_date_to": "2017-11-08", "currency": "eqc", "adname": "ToyStory48", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-10-03", "cpm": "27"},
{"username": "User2", "cpi": "11", "name": "Subaru49listing", "ask_date_to": "2017-09-12", "currency": "xqc", "adname": "Subaru49", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-10", "cpm": "33"},
{"username": "User8", "cpi": "50", "name": "ToyStory1Listing No.9", "ask_date_to": "2017-11-21", "currency": "eqc", "adname": "ToyStory1", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-09-16", "cpm": "25"},
{"username": "User9", "cpi": "43", "name": "left-for-dead2Listing No.2", "ask_date_to": "2017-10-03", "currency": "xqc", "adname": "left-for-dead2", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-02", "cpm": "29"},
{"username": "User5", "cpi": "25", "name": "Honda3Listing No.6", "ask_date_to": "2017-10-03", "currency": "eqc", "adname": "Honda3", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-09-02", "cpm": "31"},
{"username": "User9", "cpi": "38", "name": "GameOfThrones4Listing No.1", "ask_date_to": "2017-10-15", "currency": "eqc", "adname": "GameOfThrones4", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-08-11", "cpm": "23"},
{"username": "User1", "cpi": "27", "name": "left-for-dead5Listing No.2", "ask_date_to": "2017-10-26", "currency": "eqc", "adname": "left-for-dead5", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-08-20", "cpm": "19"},
{"username": "User5", "cpi": "15", "name": "left-for-dead6Listing No.9", "ask_date_to": "2017-09-15", "currency": "xqc", "adname": "left-for-dead6", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-06", "cpm": "36"},
{"username": "User5", "cpi": "27", "name": "Diningx7Listing No.9", "ask_date_to": "2017-11-21", "currency": "eqc", "adname": "Diningx7", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-09-14", "cpm": "32"},
{"username": "User7", "cpi": "32", "name": "xx8Listing No.4", "ask_date_to": "2017-10-11", "currency": "xqc", "adname": "xx8", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-08-03", "cpm": "44"},
{"username": "User3", "cpi": "44", "name": "Counterstrike9Listing No.6", "ask_date_to": "2017-12-16", "currency": "xqc", "adname": "Counterstrike9", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-10-10", "cpm": "14"},
{"username": "User1", "cpi": "15", "name": "Dining10Listing No.9", "ask_date_to": "2017-09-19", "currency": "eqc", "adname": "Dining10", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-07-09", "cpm": "42"},
{"username": "User2", "cpi": "47", "name": "Volvo11Listing No.1", "ask_date_to": "2017-08-12", "currency": "xqc", "adname": "Volvo11", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-02", "cpm": "25"},
{"username": "User5", "cpi": "43", "name": "Diningx12Listing No.2", "ask_date_to": "2017-09-17", "currency": "xqc", "adname": "Diningx12", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-07-14", "cpm": "37"},
{"username": "User5", "cpi": "34", "name": "Honda13Listing No.9", "ask_date_to": "2017-09-08", "currency": "eqc", "adname": "Honda13", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-08-02", "cpm": "24"},
{"username": "User9", "cpi": "39", "name": "newDining14Listing No.6", "ask_date_to": "2017-08-19", "currency": "xqc", "adname": "newDining14", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-07-16", "cpm": "39"},
{"username": "User8", "cpi": "29", "name": "InfinityWar15Listing No.6", "ask_date_to": "2017-09-21", "currency": "xqc", "adname": "InfinityWar15", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-07-16", "cpm": "25"},
{"username": "User1", "cpi": "11", "name": "Dota216Listing No.4", "ask_date_to": "2017-10-20", "currency": "xqc", "adname": "Dota216", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-09-19", "cpm": "40"},
{"username": "User6", "cpi": "14", "name": "ToyStory17Listing No.1", "ask_date_to": "2017-11-09", "currency": "eqc", "adname": "ToyStory17", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-09-03", "cpm": "9"},
{"username": "User8", "cpi": "18", "name": "InfinityWar18Listing No.2", "ask_date_to": "2017-08-21", "currency": "eqc", "adname": "InfinityWar18", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-07-20", "cpm": "9"},
{"username": "User2", "cpi": "12", "name": "Call-Of-Duty19Listing No.9", "ask_date_to": "2017-11-20", "currency": "eqc", "adname": "Call-Of-Duty19", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-16", "cpm": "41"},
{"username": "User1", "cpi": "33", "name": "Dota220Listing No.5", "ask_date_to": "2017-09-15", "currency": "eqc", "adname": "Dota220", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-08-14", "cpm": "5"},
{"username": "User7", "cpi": "38", "name": "Call-Of-Duty21Listing No.8", "ask_date_to": "2017-10-22", "currency": "xqc", "adname": "Call-Of-Duty21", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-08-16", "cpm": "34"},
{"username": "User5", "cpi": "37", "name": "Dining22Listing No.3", "ask_date_to": "2017-09-13", "currency": "eqc", "adname": "Dining22", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-07-10", "cpm": "23"},
{"username": "User4", "cpi": "27", "name": "GoodFellas23Listing No.4", "ask_date_to": "2017-11-09", "currency": "xqc", "adname": "GoodFellas23", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-10-06", "cpm": "22"},
{"username": "User5", "cpi": "14", "name": "GameOfThrones24Listing No.5", "ask_date_to": "2017-10-18", "currency": "xqc", "adname": "GameOfThrones24", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-09-09", "cpm": "16"},
{"username": "User9", "cpi": "16", "name": "left-for-dead25Listing No.1", "ask_date_to": "2017-11-16", "currency": "xqc", "adname": "left-for-dead25", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-10", "cpm": "36"},
{"username": "User3", "cpi": "27", "name": "GameOfThrones26Listing No.4", "ask_date_to": "2017-11-24", "currency": "xqc", "adname": "GameOfThrones26", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-09-18", "cpm": "43"},
{"username": "User5", "cpi": "36", "name": "Nissan27Listing No.6", "ask_date_to": "2017-08-19", "currency": "eqc", "adname": "Nissan27", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-14", "cpm": "48"},
{"username": "User4", "cpi": "44", "name": "Volvo28Listing No.5", "ask_date_to": "2017-10-12", "currency": "eqc", "adname": "Volvo28", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-08-08", "cpm": "40"},
{"username": "User5", "cpi": "11", "name": "newDining29Listing No.3", "ask_date_to": "2017-10-10", "currency": "eqc", "adname": "newDining29", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-09-03", "cpm": "44"},
{"username": "User5", "cpi": "43", "name": "GameOfThrones30Listing No.2", "ask_date_to": "2017-11-22", "currency": "xqc", "adname": "GameOfThrones30", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-09-19", "cpm": "46"},
{"username": "User7", "cpi": "19", "name": "Godfather31Listing No.3", "ask_date_to": "2017-08-13", "currency": "eqc", "adname": "Godfather31", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-11", "cpm": "32"},
{"username": "User3", "cpi": "40", "name": "Overwatch32Listing No.3", "ask_date_to": "2017-11-10", "currency": "eqc", "adname": "Overwatch32", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-09-02", "cpm": "45"},
{"username": "User9", "cpi": "46", "name": "GoodFellas33Listing No.1", "ask_date_to": "2017-12-14", "currency": "eqc", "adname": "GoodFellas33", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-10-11", "cpm": "24"},
{"username": "User8", "cpi": "50", "name": "Honda34Listing No.9", "ask_date_to": "2017-12-29", "currency": "eqc", "adname": "Honda34", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-10-20", "cpm": "43"},
{"username": "User3", "cpi": "28", "name": "Overwatch35Listing No.7", "ask_date_to": "2017-11-18", "currency": "eqc", "adname": "Overwatch35", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-10-16", "cpm": "38"},
{"username": "User4", "cpi": "10", "name": "GameOfThrones36Listing No.2", "ask_date_to": "2017-08-14", "currency": "eqc", "adname": "GameOfThrones36", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-08", "cpm": "48"},
{"username": "User3", "cpi": "45", "name": "Call-Of-Duty37Listing No.5", "ask_date_to": "2017-10-14", "currency": "xqc", "adname": "Call-Of-Duty37", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-09", "cpm": "8"},
{"username": "User3", "cpi": "46", "name": "Dining38Listing No.4", "ask_date_to": "2017-09-20", "currency": "eqc", "adname": "Dining38", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-07-18", "cpm": "45"},
{"username": "User4", "cpi": "19", "name": "Honda39Listing No.1", "ask_date_to": "2017-08-17", "currency": "xqc", "adname": "Honda39", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-07-10", "cpm": "19"},
{"username": "User7", "cpi": "10", "name": "InfinityWar40Listing No.8", "ask_date_to": "2017-10-24", "currency": "xqc", "adname": "InfinityWar40", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-19", "cpm": "16"},
{"username": "User3", "cpi": "44", "name": "left-for-dead41Listing No.7", "ask_date_to": "2017-09-21", "currency": "xqc", "adname": "left-for-dead41", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-07-13", "cpm": "37"},
{"username": "User7", "cpi": "30", "name": "Godfather42Listing No.4", "ask_date_to": "2017-09-17", "currency": "xqc", "adname": "Godfather42", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-07-14", "cpm": "37"},
{"username": "User3", "cpi": "25", "name": "Tesla43Listing No.3", "ask_date_to": "2017-09-14", "currency": "eqc", "adname": "Tesla43", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-07-11", "cpm": "14"},
{"username": "User2", "cpi": "15", "name": "GoodFellas44Listing No.9", "ask_date_to": "2017-11-07", "currency": "xqc", "adname": "GoodFellas44", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-09-06", "cpm": "5"},
{"username": "User8", "cpi": "40", "name": "GameOfThrones45Listing No.8", "ask_date_to": "2017-11-20", "currency": "xqc", "adname": "GameOfThrones45", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-10-15", "cpm": "29"},
{"username": "User6", "cpi": "50", "name": "half-life-346Listing No.4", "ask_date_to": "2017-10-19", "currency": "eqc", "adname": "half-life-346", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-10", "cpm": "25"},
{"username": "User2", "cpi": "47", "name": "xx47Listing No.9", "ask_date_to": "2017-10-07", "currency": "xqc", "adname": "xx47", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-08-03", "cpm": "7"},
{"username": "User2", "cpi": "46", "name": "ToyStory48Listing No.2", "ask_date_to": "2017-09-19", "currency": "xqc", "adname": "ToyStory48", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-08-17", "cpm": "12"},
{"username": "User2", "cpi": "13", "name": "Subaru49Listing No.4", "ask_date_to": "2017-09-16", "currency": "eqc", "adname": "Subaru49", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-08-09", "cpm": "46"},
{"username": "User8", "cpi": "28", "name": "ToyStory1Listing No.4", "ask_date_to": "2017-09-23", "currency": "eqc", "adname": "ToyStory1", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-08-18", "cpm": "35"},
{"username": "User9", "cpi": "33", "name": "left-for-dead2Listing No.8", "ask_date_to": "2017-10-12", "currency": "eqc", "adname": "left-for-dead2", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-06", "cpm": "16"},
{"username": "User5", "cpi": "44", "name": "Honda3Listing No.6", "ask_date_to": "2017-10-13", "currency": "eqc", "adname": "Honda3", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-08-06", "cpm": "21"},
{"username": "User9", "cpi": "39", "name": "GameOfThrones4Listing No.4", "ask_date_to": "2017-09-09", "currency": "xqc", "adname": "GameOfThrones4", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-08-02", "cpm": "49"},
{"username": "User1", "cpi": "35", "name": "left-for-dead5Listing No.3", "ask_date_to": "2017-11-18", "currency": "eqc", "adname": "left-for-dead5", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-09-09", "cpm": "27"},
{"username": "User5", "cpi": "44", "name": "left-for-dead6Listing No.5", "ask_date_to": "2017-11-23", "currency": "xqc", "adname": "left-for-dead6", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-15", "cpm": "20"},
{"username": "User5", "cpi": "41", "name": "Diningx7Listing No.7", "ask_date_to": "2017-11-05", "currency": "eqc", "adname": "Diningx7", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-10-02", "cpm": "29"},
{"username": "User7", "cpi": "19", "name": "xx8Listing No.9", "ask_date_to": "2017-09-24", "currency": "eqc", "adname": "xx8", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-07-17", "cpm": "35"},
{"username": "User3", "cpi": "15", "name": "Counterstrike9Listing No.6", "ask_date_to": "2017-12-20", "currency": "xqc", "adname": "Counterstrike9", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-10-14", "cpm": "36"},
{"username": "User1", "cpi": "27", "name": "Dining10Listing No.9", "ask_date_to": "2017-09-10", "currency": "xqc", "adname": "Dining10", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-08-04", "cpm": "9"},
{"username": "User2", "cpi": "46", "name": "Volvo11Listing No.1", "ask_date_to": "2017-11-07", "currency": "eqc", "adname": "Volvo11", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-09-02", "cpm": "29"},
{"username": "User5", "cpi": "29", "name": "Diningx12Listing No.2", "ask_date_to": "2017-11-19", "currency": "eqc", "adname": "Diningx12", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-10-13", "cpm": "40"},
{"username": "User5", "cpi": "34", "name": "Honda13Listing No.7", "ask_date_to": "2017-10-27", "currency": "eqc", "adname": "Honda13", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-09-19", "cpm": "48"},
{"username": "User9", "cpi": "12", "name": "newDining14Listing No.1", "ask_date_to": "2017-08-03", "currency": "eqc", "adname": "newDining14", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-07-01", "cpm": "7"},
{"username": "User8", "cpi": "47", "name": "InfinityWar15Listing No.1", "ask_date_to": "2017-10-25", "currency": "eqc", "adname": "InfinityWar15", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-08-20", "cpm": "37"},
{"username": "User1", "cpi": "46", "name": "Dota216Listing No.5", "ask_date_to": "2017-10-10", "currency": "eqc", "adname": "Dota216", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-08-01", "cpm": "13"},
{"username": "User6", "cpi": "13", "name": "ToyStory17Listing No.5", "ask_date_to": "2017-08-08", "currency": "eqc", "adname": "ToyStory17", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-07-07", "cpm": "41"},
{"username": "User8", "cpi": "16", "name": "InfinityWar18Listing No.5", "ask_date_to": "2017-10-06", "currency": "eqc", "adname": "InfinityWar18", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-09-05", "cpm": "37"},
{"username": "User2", "cpi": "17", "name": "Call-Of-Duty19Listing No.2", "ask_date_to": "2017-09-18", "currency": "eqc", "adname": "Call-Of-Duty19", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-07-13", "cpm": "19"},
{"username": "User1", "cpi": "48", "name": "Dota220Listing No.2", "ask_date_to": "2017-08-09", "currency": "eqc", "adname": "Dota220", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-07-01", "cpm": "18"},
{"username": "User7", "cpi": "40", "name": "Call-Of-Duty21Listing No.2", "ask_date_to": "2017-10-08", "currency": "eqc", "adname": "Call-Of-Duty21", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-01", "cpm": "22"},
{"username": "User5", "cpi": "26", "name": "Dining22Listing No.2", "ask_date_to": "2017-12-25", "currency": "xqc", "adname": "Dining22", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "ban_left", "ask_date_from": "2017-10-17", "cpm": "37"},
{"username": "User4", "cpi": "22", "name": "GoodFellas23Listing No.7", "ask_date_to": "2017-09-11", "currency": "eqc", "adname": "GoodFellas23", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-05", "cpm": "18"},
{"username": "User5", "cpi": "46", "name": "GameOfThrones24Listing No.8", "ask_date_to": "2017-11-05", "currency": "eqc", "adname": "GameOfThrones24", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-10-02", "cpm": "44"},
{"username": "User9", "cpi": "48", "name": "left-for-dead25Listing No.5", "ask_date_to": "2017-10-27", "currency": "eqc", "adname": "left-for-dead25", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-17", "cpm": "7"},
{"username": "User3", "cpi": "42", "name": "GameOfThrones26Listing No.7", "ask_date_to": "2017-10-13", "currency": "xqc", "adname": "GameOfThrones26", "msg": "We are going on an ad blitz to promote our new product .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-09-06", "cpm": "30"},
{"username": "User5", "cpi": "45", "name": "Nissan27Listing No.5", "ask_date_to": "2017-11-10", "currency": "eqc", "adname": "Nissan27", "msg": "We are looking to get the word out about our new product .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-10-03", "cpm": "26"},
{"username": "User4", "cpi": "17", "name": "Volvo28Listing No.5", "ask_date_to": "2017-12-23", "currency": "eqc", "adname": "Volvo28", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Auto", "adtype": "popup", "ask_date_from": "2017-10-17", "cpm": "19"},
{"username": "User5", "cpi": "31", "name": "newDining29Listing No.5", "ask_date_to": "2017-11-06", "currency": "xqc", "adname": "newDining29", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-09-01", "cpm": "40"},
{"username": "User5", "cpi": "41", "name": "GameOfThrones30Listing No.5", "ask_date_to": "2017-09-11", "currency": "eqc", "adname": "GameOfThrones30", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-03", "cpm": "29"},
{"username": "User7", "cpi": "42", "name": "Godfather31Listing No.1", "ask_date_to": "2017-11-20", "currency": "xqc", "adname": "Godfather31", "msg": "Your users will want to see these cool new services .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-10-15", "cpm": "23"},
{"username": "User3", "cpi": "43", "name": "Overwatch32Listing No.4", "ask_date_to": "2017-12-08", "currency": "eqc", "adname": "Overwatch32", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_right", "ask_date_from": "2017-10-06", "cpm": "31"},
{"username": "User9", "cpi": "27", "name": "GoodFellas33Listing No.1", "ask_date_to": "2017-09-11", "currency": "xqc", "adname": "GoodFellas33", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-08-06", "cpm": "43"},
{"username": "User8", "cpi": "46", "name": "Honda34Listing No.2", "ask_date_to": "2017-11-23", "currency": "xqc", "adname": "Honda34", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-09-14", "cpm": "11"},
{"username": "User3", "cpi": "48", "name": "Overwatch35Listing No.2", "ask_date_to": "2017-08-12", "currency": "xqc", "adname": "Overwatch35", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-07-09", "cpm": "29"},
{"username": "User4", "cpi": "30", "name": "GameOfThrones36Listing No.3", "ask_date_to": "2017-08-18", "currency": "eqc", "adname": "GameOfThrones36", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-07-16", "cpm": "27"},
{"username": "User3", "cpi": "17", "name": "Call-Of-Duty37Listing No.1", "ask_date_to": "2017-10-22", "currency": "eqc", "adname": "Call-Of-Duty37", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Gaming", "adtype": "ban_left", "ask_date_from": "2017-09-15", "cpm": "36"},
{"username": "User3", "cpi": "19", "name": "Dining38Listing No.6", "ask_date_to": "2017-11-19", "currency": "eqc", "adname": "Dining38", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Porn", "adtype": "popup", "ask_date_from": "2017-10-09", "cpm": "10"},
{"username": "User4", "cpi": "27", "name": "Honda39Listing No.6", "ask_date_to": "2017-11-15", "currency": "xqc", "adname": "Honda39", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-10-13", "cpm": "11"},
{"username": "User7", "cpi": "11", "name": "InfinityWar40Listing No.5", "ask_date_to": "2017-10-10", "currency": "eqc", "adname": "InfinityWar40", "msg": "We are going on an ad blitz to promote our new product .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_left", "ask_date_from": "2017-09-08", "cpm": "16"},
{"username": "User3", "cpi": "16", "name": "left-for-dead41Listing No.9", "ask_date_to": "2017-11-20", "currency": "xqc", "adname": "left-for-dead41", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-09-11", "cpm": "12"},
{"username": "User7", "cpi": "13", "name": "Godfather42Listing No.8", "ask_date_to": "2017-08-15", "currency": "xqc", "adname": "Godfather42", "msg": "Your users will want to see these cool new services .Have our ads featured on your awesome website!.", "genre": "Movies", "adtype": "ban_right", "ask_date_from": "2017-07-12", "cpm": "18"},
{"username": "User3", "cpi": "43", "name": "Tesla43Listing No.4", "ask_date_to": "2017-09-23", "currency": "eqc", "adname": "Tesla43", "msg": "This is a product you will be thrilled to show your users .Feature us on your website.", "genre": "Auto", "adtype": "ban_top_wide", "ask_date_from": "2017-07-15", "cpm": "26"},
{"username": "User2", "cpi": "34", "name": "GoodFellas44Listing No.9", "ask_date_to": "2017-09-19", "currency": "eqc", "adname": "GoodFellas44", "msg": "We are going on an ad blitz to promote our new product .Introduce us to your amazing audience!.", "genre": "Movies", "adtype": "popup", "ask_date_from": "2017-08-09", "cpm": "35"},
{"username": "User8", "cpi": "40", "name": "GameOfThrones45Listing No.2", "ask_date_to": "2017-11-17", "currency": "eqc", "adname": "GameOfThrones45", "msg": "We are looking to get the word out about our new product .Feature us on your website.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-09-07", "cpm": "49"},
{"username": "User6", "cpi": "36", "name": "half-life-346Listing No.2", "ask_date_to": "2017-11-22", "currency": "xqc", "adname": "half-life-346", "msg": "We are looking to get the word out about our new product .Introduce us to your amazing audience!.", "genre": "Gaming", "adtype": "popup", "ask_date_from": "2017-10-20", "cpm": "44"},
{"username": "User2", "cpi": "16", "name": "xx47Listing No.2", "ask_date_to": "2017-10-12", "currency": "xqc", "adname": "xx47", "msg": "This is a product you will be thrilled to show your users .Have our ads featured on your awesome website!.", "genre": "Porn", "adtype": "ban_top_wide", "ask_date_from": "2017-08-05", "cpm": "35"},
{"username": "User2", "cpi": "13", "name": "ToyStory48Listing No.3", "ask_date_to": "2017-09-17", "currency": "xqc", "adname": "ToyStory48", "msg": "Your users will want to see these cool new services .Feature us on your website.", "genre": "Movies", "adtype": "ban_top_wide", "ask_date_from": "2017-08-15", "cpm": "39"},
{"username": "User2", "cpi": "42", "name": "Subaru49Listing No.9", "ask_date_to": "2017-11-22", "currency": "xqc", "adname": "Subaru49", "msg": "This is a product you will be thrilled to show your users .Introduce us to your amazing audience!.", "genre": "Auto", "adtype": "ban_right", "ask_date_from": "2017-09-16", "cpm": "30"}
];
adlistingsDisplay =[];
  constructor(private trackCurrency:TrackCurrency,private marketplaceService : MarketplaceService) {
this.dt1 = new Date(2017,7,12);
this.dt2 = new Date(2017,10,8);
this.array = new Array(this.size);
this.array2= new Array(this.adlistings.length);
for (var i = 0; i < this.array2.length; i++) {
this.array2[i] = i;}
for (var i = 0; i < this.size; i++) {
this.array[i] = i;
   }

}
  ngOnInit() {
this.trackCurrency.getCurrency().subscribe(
  returnedValue => {this.currencyType = returnedValue;
  });
  }
  updateGenre(genre:any){
this.genre = genre;
  }
  updateAdtype(adtype:any){
this.Adtype = adtype;
  }
  onSubmit(){
this.filterUsed = true;
this.selectedList = [];
for (var i = 0; i < this.adlistings.length; i++) {
  var firstDate = new Date(this.adlistings[i]["ask_date_from"])
  if( (this.genre === this.adlistings[i]["genre"]) && (firstDate >= this.dt1) && ( (parseInt(this.adlistings[i]["cpi"]) >= this.rangeValues2[0]) && ( parseInt(this.adlistings[i]["cpi"]) <= this.rangeValues2[1]))) {
if( (parseInt(this.adlistings[i]["cpm"]) >= this.rangeValues3[0]) && ( parseInt(this.adlistings[i]["cpm"]) <= this.rangeValues3[1]) && (this.trackCurrency.currency.toLowerCase() == this.adlistings[i]["currency"])){
  //if((this.adlistings[i]["adtype"] =='ban_left' && this.Adtype == 'Banner Left') || (this.adlistings[i]["adtype"] =='ban_top_wide' && this.Adtype == 'Banner Top') || (this.adlistings[i]["adtype"] =='ban_right' && this.Adtype == 'Banner Right') || (this.adlistings[i]["adtype"] =='popup' && this.Adtype == 'Popup') ){
    this.selectedList.push(this.adlistings[i]);
  //}
}

}
}

this.size = this.selectedList.length;


this.array = new Array(this.size);
for (var i = 0; i < this.size; i++) {
  this.array[i] = i;
}
}}
